version: '3'
services:
  terraform:
    build:
      context: .
      dockerfile: ./docker/terraform/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${QT_AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${QT_AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./docker/terraform/src:/root/src

