variable "env" {}
variable "lambda_container_role_arn" {}
variable "aws_iam_role_iam_for_api_gateway_arn" {}
variable "db_host" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "rds_proxy_endpoint" {}
variable "bucket_name" {}
variable "lambda-scanner-image-url" {}
variable "lambda-ocr-cutout-image-url" {}
variable "lambda-ocr-predict-image-url" {}
variable "aws_security_group_lambda_id" {}
variable "private_subnet_1_id" {}
variable "private_subnet_2_id" {}
variable "aws_vpc_endpoint_lambda_dns" {}
variable "aws_vpc_endpoint_api_gateway_id" {}
variable "aws_iam_role_rds_lambda_invoke_role_id" {}
