variable "env" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "db_sg_id" {}
variable "db_subnet_group_name" {}
variable "lambda_container_role_arn" {}
variable "private_subnet_1_id" {}
variable "private_subnet_2_id" {}
variable "aws_iam_role_rds_proxy_role_arn" {}
variable "aws_security_group_rds_proxy_id" {}
