name: Develop CI

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.7.0']
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Docker Container Create
      run: |
        docker-compose -f docker-compose.ci.yml build \
        --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
        --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
        --build-arg BUCKET_NAME=${{ secrets.BUCKET_NAME }} \
        --build-arg DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
        --build-arg IMAGE_SCAN_API_URL="${{ secrets.IMAGE_SCAN_API_URL }}" \
        --build-arg DB_HOST=db \
        --build-arg DB_NAME=test_test \
        --build-arg DB_USER=root \
        --build-arg DB_PASS=test
        docker-compose -f docker-compose.ci.yml up -d
        sleep 20s
        docker ps -a
    - name: Set up Mysql for mysql8.0
      run: |
        docker exec -t qumitoru-mysql mysql -u root -ptest -e"ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'test';"
    - name: Install vue/cli-service
      run: |
        docker exec -t qumitoru-vue npm i @vue/cli-service
    - name: Execute PyTests(Unit test)
      run: |
        docker exec -t qumitoru-django pytest
    - name: Execute Jest(Unit test)
      run: |
        docker exec -t qumitoru-vue npm run test:unit
    - name: Execute NightWatch(E2E test)
      run: |
        docker exec -t qumitoru-vue npm run test:e2e
